{% set name = "yardang" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/y/yardang/yardang-{{ version }}.tar.gz
  sha256: 83980608bbad9e7b98a5aebd2e43f0897ff2fb155567fde5fe29923f6546e6f6

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  entry_points:
    - yardang = yardang.cli:main

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - autodoc-pydantic
    - furo
    - myst-parser
    - packaging
    - rich
    - sphinx >=7.2.6,<8.1
    - sphinx-autoapi
    - sphinx-copybutton
    - sphinx-design
    - toml
    - typer

test:
  requires:
    - pip
  commands:
    - pip check
    - yardang --help
  imports:
    - yardang.build
    - yardang.cli

about:
  home: http://github.com/python-project-templates/yardang
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Easily generate sphinx documentation
  description: Easily generate sphinx documentation
  dev_url: https://github.com/python-project-templates/yardang

extra:
  recipe-maintainers:
    - timkpaine
